// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {app} from '../models';

export function GetConfig():Promise<config.File>;

export function LoadPlanner(arg1:string):Promise<app.PlannerPayload>;

export function PingAuth():Promise<string>;

export function RecalculatePlanner(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<app.PlannerSummary>;

export function SaveConfig(arg1:config.File):Promise<void>;
