// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LoadPlanner(arg1) {
  return window['go']['main']['App']['LoadPlanner'](arg1);
}

export function PingAuth() {
  return window['go']['main']['App']['PingAuth']();
}

export function RecalculatePlanner(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RecalculatePlanner'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
